[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "supervenn"
version = "0.5.0"
description = "supervenn is a tool for visualization of relations of many sets using matplotlib"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Fedor Indukaev", email = "gecko984@gmail.com" },
]
dependencies = [
    "numpy>=2.1.0",
    "matplotlib>=3.9.3",
    "pandas>=2.2.3",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
]

[project.urls]
Homepage = "https://github.com/gecko984/supervenn"

[tool.setuptools.packages.find]
include = ["supervenn*"]
